-- ============================================================
-- Seller Product Category Dependence Analysis
-- ============================================================

-- Question:
-- How diversified are sellers across product categories?
-- Which product category generates the most revenue for each
-- seller, and how dependent is each seller on that category?

-- Revenue is first aggregated for each seller and product
-- category combination.

-- The number of product categories and total revenue are then
-- calculated for each seller.

-- Product categories are ranked within each seller based on
-- category revenue to identify the seller's highest-revenue
-- category.

-- Top category revenue share represents the percentage of a
-- seller's total revenue generated by their highest-revenue
-- product category.

WITH Table_1 AS
(
	SELECT O1.seller_id, product_category_name,
	SUM(price) as category_revenue
	FROM olist_order_items_dataset AS O1
	INNER JOIN olist_products_dataset AS O2
	ON O1.product_id = O2.product_id
	GROUP BY seller_id, product_category_name
), Table_2 AS
(
	SELECT *,
	COUNT(*) OVER(PARTITION BY seller_id) as no_of_categories,
	SUM(category_revenue) OVER(PARTITION BY seller_id) as total_seller_revenue,
	DENSE_RANK() OVER(PARTITION BY seller_id ORDER BY category_revenue DESC) as rank_product
	FROM Table_1
)
SELECT seller_id, no_of_categories, product_category_name as top_category,
ROUND((category_revenue/total_seller_revenue)*100,2) as top_category_revenue_share
FROM Table_2
WHERE rank_product = 1;