-- ============================================================
-- Seller Revenue Concentration Analysis
-- ============================================================

-- Question:
-- How concentrated is revenue among sellers?
-- What percentage of total revenue is generated by each seller,
-- and how quickly does cumulative revenue increase among the
-- highest-revenue sellers?

-- Revenue is calculated using the price of products sold by
-- each seller.

-- Each seller's revenue share is calculated as a percentage
-- of total product revenue.

-- Sellers are ordered from highest to lowest revenue share,
-- and cumulative revenue percentage is calculated to measure
-- how concentrated total revenue is among sellers.

WITH Table_1 AS
(
	SELECT order_id, seller_id, price, SUM(price) OVER() as total_revenue, SUM(price) OVER(PARTITION BY seller_id) as seller_revenue
	FROM olist_order_items_dataset as O1
), Table_2 AS
(
	SELECT DISTINCT seller_id, seller_revenue, total_revenue, ROUND((seller_revenue/total_revenue)* 100,3) as percent_share
	FROM Table_1
)
SELECT *, ROUND(SUM(percent_share) OVER(ORDER BY percent_share DESC),3) as cumulative_percent_share
FROM Table_2;