-- ============================================================
-- Top Product Category by Customer State Analysis
-- ============================================================

-- Question:
-- Which product category generates the most revenue in each
-- customer state?
-- What percentage of each state's total product revenue is
-- generated by its highest-revenue product category?

-- Order items are first connected with product information to
-- identify the product category associated with each item.

-- Orders are then connected to the order items, followed by
-- customer information to determine the customer state.

-- Product revenue is calculated for each product category
-- within each customer state using the item price.

-- Total product revenue is also calculated for each customer
-- state to determine the contribution of individual categories.

-- Product categories are ranked within each state according
-- to their revenue using DENSE_RANK().

-- Only the highest-revenue product category in each state is
-- retained in the final result.

-- The percentage share represents how much of the state's
-- total product revenue is generated by its top category.

WITH Table_1 AS
(
	SELECT O1.order_id, O1.product_id, O1.price, product_category_name
	FROM olist_order_items_dataset AS O1
	INNER JOIN olist_products_dataset AS O2
	ON O1.product_id = O2.product_id
), Table_2 AS
(
	SELECT T2.order_id, T2.customer_id, product_category_name, price
	FROM Table_1 as T1
	RIGHT JOIN olist_orders_dataset AS T2
	ON T1.order_id = T2.order_id
), Table_3 AS
(
	SELECT customer_state, product_category_name, price, 
	ROUND(SUM(price) OVER(PARTITION BY customer_state, product_category_name),2) as revenue_per_state_per_product,
	ROUND(SUM(price) OVER(PARTITION BY customer_state),2) as revenue_per_state
	FROM Table_2 AS T1
	INNER JOIN olist_customers_dataset AS T2
	ON T1.customer_id = T2.customer_id
), Table_4 AS
(
	SELECT *, dense_rank() OVER(PARTITION BY customer_state ORDER BY revenue_per_state_per_product DESC) as ranked_product_revenue_per_state
	FROM Table_3
), Table_5 AS
(
	SELECT DISTINCT customer_state, product_category_name, revenue_per_state_per_product, 
	revenue_per_state, ranked_product_revenue_per_state, 
	ROUND((revenue_per_state_per_product/revenue_per_state)*100,2) AS percent_share_of_product_in_state
	FROM Table_4
	WHERE ranked_product_revenue_per_state = 1
)
SELECT customer_state, product_category_name AS top_category, 
revenue_per_state_per_product AS category_revenue, percent_share_of_product_in_state
FROM Table_5;

